### ISSUE TITLE
feature request/bug?: screenshot visibility

### ISSUE THREAD

**Issue by ckohnke** [Eternita-S/Splatoon#15]
Not sure if this is an XIV, Dalamud, or Splatoon thing, but I would like to take HUD-less screenshots with the elements drawn by Splatoon being visible to help make visual guides for friends. Currently, taking an XIV screenshot does not capture the splatoon elements (though the elements appear on the PrtSc grab as expected -- other plugins, like JobBars, can appear in native XIV screenshots). Similarly, going into HUD-less mode removes all drawn splatoon elements, which then can't be captured in any way.

If possible, it'd be nice to be able to force splatoon to draw elements while in HUD-less mode (toggle on/off?). That way PrtSc can grab a capture of the screen that can then be used for guides and such. If any of the below are possible, I think it'd be a nice boon.

- splatoon elements appear in hud-less mode (PrtSc capture)
- splatoon elements can be captured by native XIV screenshot
- splatoon elements appear in hud-less mode and can be captured by native XIV screenshots

Also Splatoon is like my favorite plugin, thanks for the hard work! 😃

**Comment by Eternita-S** [comment]
Hello!
Thank you for your feedback.
> splatoon elements appear in hud-less mode (PrtSc capture)

This is possible and will be added in next update as an option.
> other plugins, like JobBars, can appear in native XIV screenshots

Whether elements added by plugins can be captured by native xiv screenshots depends on method by which they were added. Splatoon uses a method that can't be captured by native XIV's screenshots.
