### ISSUE TITLE
[suggestion] Trigger from battle log

### ISSUE THREAD

**Issue by voetre** [Eternita-S/Splatoon#17]
Im not sure if this is already something you can achieve with the trigger system you have implemented already, but I haven't been able to get it to work.

E.g. Battle log line reads 'Shiva readies Scythe Kick.' -> overlay 'E8 - Scythe Kick' is enabled.

I know you could probably achieve this with triggernometry and the HTTP API, but something backed in would be good to have.

**Comment by Eternita-S** [comment]
Hello!
You should be able to do any trigger based off anything that you can see in chat, including battle log.
Can you send me your layout? I'll try to see if there are any problems with it. (use copy - export to clipboard function)

**Comment by voetre** [comment]
Hey Eternita,

Apologies for the delay (22 days? yikes...) I have exported the config below:

`E8 - Scythe Kick~{"ZoneLockH":[905],"DCond":1,"Elements":{"Radius":{"type":1,"refX":93.07869,"refY":112.01788,"radius":5.21,"color":3355508515,"thicc":5.3,"refActorName":"Shiva","onlyVisible":true}},"UseTriggers":true,"Triggers":[{"Type":2,"Duration":10,"Match":"Shiva readies Scythe Kick."}]}`

I want to have the layout only trigger when she begins casting Scythe Kick, the logline being "Shiva readies Scythe Kick."

however, currently it shows always when in combat.

the goal would be:

1. Shiva readies scythe kick
2. circle marker appears
3. duration expires of  X seconds
4. circle marker disappears

Is this feasible using the GUI?

**Comment by voetre** [comment]
I reviewed the layout and managed to find the issue! sorry for the hassle!
