### ISSUE TITLE
Preset: Multiple presets in one issue because I'm lazy

### ISSUE THREAD

**Issue by Em-Six** [Eternita-S/Splatoon#18]
Short description: 20yalm ring around target for melee gap closers

```20y Ring~{"ZoneLockH":[],"DCond":4,"Elements":{"20y Ring":{"type":1,"refX":-588.177,"refY":-840.44836,"refZ":30.110699,"radius":20.0,"refActorType":2,"includeHitbox":true,"includeOwnHitbox":true}},"JobLock":158916411392,"Triggers":[]}```

Short description: 3yalm ring around target for GCD range and a 2yalm ring around the target for auto attack range (auto attacks are a large portion of your damage, don't lose them)

```Melee Range~{"ZoneLockH":[],"Elements":{"Auto Attack":{"type":1,"refX":-584.84045,"refY":-842.6976,"refZ":30.110699,"radius":2.0,"refActorType":2,"includeHitbox":true,"includeOwnHitbox":true},"GCD Range":{"type":1,"refX":-584.7163,"refY":-842.6814,"refZ":30.110699,"radius":3.0,"refActorType":2,"includeHitbox":true,"includeOwnHitbox":true},"pixel perfect":{"type":1,"Enabled":false,"refX":-594.2895,"refY":-836.6198,"refZ":30.07,"radius":0.0,"refActorType":1}},"Triggers":[]}```

Short description: Ground markers for Hydaelyn Ex's Sword attack where you go in intercardinals

```Hydaelyn~{"ZoneLockH":[996],"DCond":5,"Elements":{"Cross Marks":{"type":3,"refY":10.0,"offY":-10.0,"radius":0.0,"color":1677721855,"refActorType":2,"includeHitbox":true,"includeRotation":true},"Cross Horizontal":{"type":3,"refY":10.0,"offY":-10.0,"radius":0.0,"color":1677721855,"refActorType":2,"includeHitbox":true,"includeRotation":true,"AdditionalRotation":1.5707964}},"UseTriggers":true,"Triggers":[{"Type":2,"Duration":4,"Match":"gains the effect of heros"}]}```

Short description: Marks a 5yalm ring around the adds in Zodiark so that you can find the aoe sweet spot to hit all 4 adds easily

```Zodiark~{"ZoneLockH":[993],"Elements":{"Roiling Darkness":{"type":1,"refX":-603.3536,"refY":-842.1655,"refZ":30.019999,"radius":5.0,"refActorName":"Roiling Darkness","includeHitbox":true}},"Triggers":[]}```

**Comment by Eternita-S** [comment]
Thank you very much! Added presets.
