### ISSUE TITLE
ground-relative width option for `line between two fixed coordinates`

### ISSUE THREAD

**Issue by LastExceed** [Eternita-S/Splatoon#27]
for a given `line relative to object position` there is 2 ways to configure the width of the line:
* `thickness` is camera-relative, meaning that the line always has the same width on screen, regardless of the perspective from which you look at the line. this is useful for visibility
* `radius` is ground-relative, meaning that the line looks like a rectangle painted on the ground. this is useful for precise positioning

would be nice if we could have a ground-relative width option for `line between two fixed coordinates` as well

**Comment by Eternita-S** [comment]
Hello!
There will be eventually proper rectangle shapes. But, due to lack of time right now, I'm holding off major features until my schedule will be more free.

**Comment by LastExceed** [comment]
i'm actually looking into implementing this myself right now, just creating an issue for tracking and discussion purposes

**Comment by Eternita-S** [comment]
just fyi current implementation of "radius" for line is extremely cursed and was made as temporary and fast solution to simplify couple mechanics

**Comment by LastExceed** [comment]
ok i spent an hour on this and give up now. too much spaghetti

**Comment by Eternita-S** [comment]
https://github.com/Eternita-S/Splatoon/issues/30 prevents this from being correctly implemented

**Comment by Eternita-S** [comment]
As a temporary solution I have added possibility of using radius on lines on the ground. They are subject to distortion when crossing corner of the screen, however, and will remain until mentioned bug is fixed or workaround for it found.
