### ISSUE TITLE
Auto-attack range is actually 2.1, for preset

### ISSUE THREAD

**Issue by Grammernatzi** [Eternita-S/Splatoon#28]
Just thought I'd mention this (I've confirmed it via testing), as this actually has come in handy for certain fights where I could just barely be in auto range. With the current preset, it'd show the safe zone as not being in auto attack range, but with 2.1 it shows it actually is (and I could confirm it because I could see the autos coming out). Not too big of a deal but it'd probably just be helpful for users who just copy the preset and don't adjust it.

**Comment by Eternita-S** [comment]
Thank you! Changed it.
