### ISSUE TITLE
Issue: transforming off-screen world coordinates to screen coordinates can result in invalid values

### ISSUE THREAD

**Issue by Eternita-S** [Eternita-S/Splatoon#30]
Unfortunately there is a bug in the game function that splatoon relies on which creates big obstacles when it comes to custom shapes, including cones and rectangles. This is also why polygons are not and thing yet and why lines with radius will be distorted when they are crossing corner of the screen. 

Using world to screen function on points behind the screen results in such points being calculated to invalid coordinates. Like this:
https://imgur.com/a/4pkgiYL
This is what happens if point of a line is behind the screen. For recording this example I've disabled workaround that fixes this issue, you shouldn't be able to recreate it.
However when it comes to shapes more complex than line I don't know how to transform them to be within visible boundaries. This is what majorly prevents further development of the plugin - even if it is possible to do transformation like this, I don't yet know how.
Example of transformations that needs to be done:
![image](https://user-images.githubusercontent.com/5073202/158990539-a976d824-da65-4b07-bd91-6bc62fd5f51a.png)
On a positive note going just a bit behind the screen does not results in any problems, only relatively far distances will cause problems.

Additional problem is that the transformation must be done with game coordinates, before they have been converted to screen coordinates. So basically we need to transform in-game coordinates that way so when they are converted to screen coordinates  they would result correctly cut shape.

Again, at this point of time I don't know how to approach this problem. It would be really good if someone could help me with algorithm.

_Originally posted by @Eternita-S in https://github.com/Eternita-S/Splatoon/issues/14#issuecomment-1072299985_

**Comment by SashaFFXIV** [comment]
I'm not nearly knowledgeable enough to even begin to approach this issue, but I do know of a plugin that draws shapes similarly to this one that is able to draw cones and rectangles. [ActionEffectRange](https://github.com/yomishino/FFXIVActionEffectRange) is a third party plugin that attempts to display the AoE of executed actions and has support for abilities that use cones and rectangles.

Not sure if this is helpful or not but hopefully it is.

**Comment by Eternita-S** [comment]
Closed as impossible to resolve
