### ISSUE TITLE
A question about aplatoon

### ISSUE THREAD

**Issue by bcj88796** [Eternita-S/Splatoon#31]
i am a chinese player so maybe my english is poor  i try my best to ask this question 
6.0 before i use 1.0.2.1  i use splatoon to keep a record about deep dungeon
but 6.0 after 1.0.2.1 is not support to use .so i change 1.0.3.3 ,i copy Splatoon.dll.config to 1.0.3.3‘s ’document ,but new Marks are diffdifferent to old mark,can you help me solve this question mr Eternita-S?

**Comment by bcj88796** [comment]
Mow A few of marks is on the sky i shouldn't how to use this settings

**Comment by Eternita-S** [comment]
Hello. 
Generally, markers from new versions may be not compatible with old ones.
Is there a problem with using most recent version of Splatoon on Chinese version of the game?

**Comment by bcj88796** [comment]
> Hello. Generally, markers from new versions may be not compatible with old ones. Is there a problem with using most recent version of Splatoon on Chinese version of the game?

no have ,but i really want to have my old Splatoon.dll.config, so i come to ask mr eternita ，Do you have a solution?

**Comment by Eternita-S** [comment]
Old configurations should be fully compatible with new plugin versions.
If you have issues with it, can you post a screenshot and attach your configuration file? And I will see if I can do something.

**Comment by bcj88796** [comment]
![Uploading QQ截图20220319211146(1).png…]()

**Comment by bcj88796** [comment]
![QQ截图20220319211021](https://user-images.githubusercontent.com/36688160/159122574-4ef3e6f7-f9b6-4e3e-b915-af7ff969fac3.png)

**Comment by Eternita-S** [comment]
This is not a configuration file. Configuration file is located at: `%appdata%\XIVLauncher\pluginConfigs\Splatoon.json`

**Comment by bcj88796** [comment]
![QQ截图20220319211647](https://user-images.githubusercontent.com/36688160/159122747-b358bc6f-8cd4-45d3-91bd-bb38245ca019.png)

**Comment by Eternita-S** [comment]
can you also attach your files:
- `%appdata%\XIVLauncher\dalamud.log`
- `%appdata%\XIVLauncher\pluginConfigs\Splatoon.json`
