### ISSUE TITLE
A question about aplatoon 

### ISSUE THREAD

**Issue by bcj88796** [Eternita-S/Splatoon#32]
sorry i make a mistake

**Comment by bcj88796** [comment]
![QQ截图20220319212842](https://user-images.githubusercontent.com/36688160/159123138-13f7a54f-661c-4001-97c8-23984a5d2865.png)

**Comment by bcj88796** [comment]
it is no any circle！ i can't understand

**Comment by bcj88796** [comment]
![QQ截图20220319213411](https://user-images.githubusercontent.com/36688160/159123238-dcde13da-1e4b-4e6c-89ce-87ed8355210b.png)

**Comment by bcj88796** [comment]
![QQ截图20220319213427](https://user-images.githubusercontent.com/36688160/159123244-c51ada9d-1ee0-40fd-9f18-5015a5fcf538.png)

**Comment by bcj88796** [comment]
i do not know how to send a file ,this web can not support type

**Comment by bcj88796** [comment]
i use old 1.0.2.1 is running!before  but 6.0 after can not use 1.0.2.1

**Comment by bcj88796** [comment]
if i "zone lock " choose current zone ,mark is mistaken
![QQ截图20220319215523](https://user-images.githubusercontent.com/36688160/159124088-679ef87c-9d18-4b95-83a2-c49eaa8ccc0b.png)

**Comment by Eternita-S** [comment]
can you attach these files?
- `%appdata%\XIVLauncher\dalamud.log`
- `%appdata%\XIVLauncher\pluginConfigs\Splatoon.json`
you can use one of these file exchange services:
https://dropmefiles.com/
https://wormhole.app/

**Comment by bcj88796** [comment]
%appdata%\XIVLauncher\dalamud.log is not found it .
other Splatoon.json is under
https://wormhole.app/LR4aK#kI1wKmVkLmmmv4M6TGWaHA

**Comment by bcj88796** [comment]
![QQ截图20220320113243](https://user-images.githubusercontent.com/36688160/159146858-89a90ebf-4162-44ec-a64c-27a94ca17da1.png)

**Comment by Eternita-S** [comment]
Hello again!
I'm sorry, but unfortunately I will be unable to help you with deep dungeon as this is content that I do not do and have no means to test.

**Comment by Eternita-S** [comment]
It would appear that Y and Z coordinates may be swapped in your preset due to using old version with new Dalamud. Swapping them may fix it. If you will provide me your fresh Splatoon.json, I will do so for you so you can test it.

**Comment by Eternita-S** [comment]
please reopen if necessary
