### ISSUE TITLE
Lines disappearing when not in LoS?

### ISSUE THREAD

**Issue by Dedoooo** [Eternita-S/Splatoon#35]
i've been noticing this issue for a while and i'm not sure if this is how it's meant to be working 😅 
does it not draw the lines even if you're not facing the direction of the object you're looking for?

**Comment by Dedoooo** [comment]
okay so, i messed around with the settings and in the Debug tab there's a "Disable line fix" box and after ticking it lines seem to be working even when not in LoS. is enabling this gonna be a problem?

**Comment by Eternita-S** [comment]
Hello.
Does your line has radius?
Lines that have radius must have one of their end fully visible, or they won't work.
Disabling line fix will cause major problems for you. 
You might have better time if you increase line segments in general settings.

Please send your layout that you have problem with, screenshot of it in a position where line is not visible and screenshot of Splatoon's debug tab, so I can check if there are any extra problems

**Comment by magejiaaa** [comment]
Excuse me, I have a similar problem, why the plugin is only displayed in a small part of the left side of the screen?
Already tried deleting the Splatoon folder and reinstalling.

Like this🙏🙏 Thanks

![This is an image](https://i.imgur.com/AMcAz6j.png)

**Comment by Eternita-S** [comment]
@magejiaaa , hello. Can you post your layout please?

**Comment by magejiaaa** [comment]
> @magejiaaa，你好。你可以發布你的佈局嗎？

非常不好意思><
目前為了測試只有導入這個數據
Filled勾選後還是有同樣的問題
`
Player dot~{"Elements":{"AOE circle":{"type":1,"radius":8.93,"refActorType":1,"includeOwnHitbox":true,"Filled":true},"Player dot":{"type":1,"radius":0.0,"refActorType":1}}}
`
![layout](https://i.imgur.com/Q6IHw2w.jpg)

另外我在另一台可以使用的電腦上，發現不同的地方
Messagge concurrency左邊的數字
可使用的電腦顯示"3"
但出問題的電腦顯示"1"
不知道有沒有關聯

謝謝您😭🙏🙏
![Messagge concurrency](https://i.imgur.com/II8kRhN.jpg)

**Comment by Eternita-S** [comment]
It appears that there is a bug with multiscreen setups/windowed mode.
Please try updating to version 1.0.7.3 and see if it fixes the problem.
(Update will be available in 5-10 minutes from now)

**Comment by magejiaaa** [comment]
> It appears that there is a bug with multiscreen setups/windowed mode. Please try updating to version 1.0.7.3 and see if it fixes the problem. (Update will be available in 5-10 minutes from now)

After the update it works successfully, thank you very much! !🥰🥰

**Comment by Dedoooo** [comment]
> It appears that there is a bug with multiscreen setups/windowed mode. Please try updating to version 1.0.7.3 and see if it fixes the problem. (Update will be available in 5-10 minutes from now)

Thank you @Eternita-S this has resolved all the issues i've been experiencing
