### ISSUE TITLE
Auto-Attack range preset is incorrect (or describing the wrong thing).

### ISSUE THREAD

**Issue by SashaFFXIV** [Eternita-S/Splatoon#50]
The preset that displays Auto-Attack range is set to 2.1 yalms. Player Auto-Attack range is 3.1 yalms (as seen in pictures) and has been for quite some time (was changed sometime in HW or SB if I remember correctly).

2.1 Yalm Ring
![image](https://user-images.githubusercontent.com/55117631/172514834-a8329818-95cf-4cfc-a1dc-9ed5347b96bd.png)

3.1 Yalm Ring
![image](https://user-images.githubusercontent.com/55117631/172515078-901296c7-0024-4a04-a125-8851bc7d5b3c.png)

However, displaying a ring at 2.1 yalms can still be useful for tanks as that is the Auto-Attack range of most melee enemies and can be used to tell the distance at which an enemy will start moving when you move away from them.

**Comment by Eternita-S** [comment]
Hello!
Would you be able to fix either preset itself or it's description?
I do not play melee jobs so unfortunately I can't really test things related to them well.

**Comment by SashaFFXIV** [comment]
Honestly I think it might be better to make everything but the melee GCD ring off by default. Since Auto-Attack range is longer than Melee action range it's not actually that useful to see it since if you're in range to hit a melee GCD you'll always be in range to Auto-Attack. And while seeing the Auto-Attack range of enemies might be useful to a tank, it's not that useful for non-tanks.

I decided to take the time to add all the features into one Layout. I also added some extra conditional layouts that only appear on jobs where the element is applicable.

Attack Range Rings (Universal)
```
Attack Range Rings~{"Elements":{"Melee Action Range":{"type":1,"radius":3.0,"color":4294967295,"refActorType":2,"includeHitbox":true,"includeOwnHitbox":true},"Melee Auto-Attack Range":{"type":1,"Enabled":false,"radius":3.1,"color":4294967295,"refActorType":2,"includeHitbox":true,"includeOwnHitbox":true},"Enemy Auto-Attack Range":{"type":1,"Enabled":false,"radius":2.1,"color":4294967295,"refActorType":2,"includeHitbox":true,"includeOwnHitbox":true},"Pixel Perfect":{"type":1,"Enabled":false,"radius":0.0,"color":4227858431,"refActorType":1},"Positional Line 1":{"type":3,"Enabled":false,"refY":3.0,"radius":0.0,"color":4294967295,"refActorType":2,"includeRotation":true,"AdditionalRotation":0.7853982,"LineAddHitboxLengthYA":true,"LineAddPlayerHitboxLengthYA":true},"Positional Line 2":{"type":3,"Enabled":false,"refY":3.0,"radius":0.0,"color":4294967295,"refActorType":2,"includeRotation":true,"AdditionalRotation":2.3561945,"LineAddHitboxLengthYA":true,"LineAddPlayerHitboxLengthYA":true},"Positional Line 3":{"type":3,"Enabled":false,"refY":3.0,"radius":0.0,"color":4294967295,"refActorType":2,"includeRotation":true,"AdditionalRotation":3.9269907,"LineAddHitboxLengthYA":true,"LineAddPlayerHitboxLengthYA":true},"Positional Line 4":{"type":3,"Enabled":false,"refY":3.0,"radius":0.0,"color":4294967295,"refActorType":2,"includeRotation":true,"AdditionalRotation":5.497787,"LineAddHitboxLengthYA":true,"LineAddPlayerHitboxLengthYA":true},"6y Ring":{"type":1,"Enabled":false,"radius":6.0,"color":4294967295,"refActorType":2,"includeHitbox":true,"includeOwnHitbox":true},"20y Ring":{"type":1,"Enabled":false,"radius":20.0,"color":4294967295,"refActorType":2,"includeHitbox":true,"includeOwnHitbox":true}}}
```
Attack Range Rings (Melee Jobs Only)
```
Attack Range Rings (Melee Jobs Only)~{"Elements":{"Melee Action Range":{"type":1,"radius":3.0,"color":4294967295,"refActorType":2,"includeHitbox":true,"includeOwnHitbox":true},"Melee Auto-Attack Range":{"type":1,"Enabled":false,"radius":3.1,"color":4294967295,"refActorType":2,"includeHitbox":true,"includeOwnHitbox":true},"Enemy Auto-Attack Range":{"type":1,"Enabled":false,"radius":2.1,"color":4294967295,"refActorType":2,"includeHitbox":true,"includeOwnHitbox":true},"Positional Line 1":{"type":3,"Enabled":false,"refY":3.0,"radius":0.0,"color":4294967295,"refActorType":2,"includeRotation":true,"AdditionalRotation":0.7853982,"LineAddHitboxLengthYA":true,"LineAddPlayerHitboxLengthYA":true},"Positional Line 2":{"type":3,"Enabled":false,"refY":3.0,"radius":0.0,"color":4294967295,"refActorType":2,"includeRotation":true,"AdditionalRotation":2.3561945,"LineAddHitboxLengthYA":true,"LineAddPlayerHitboxLengthYA":true},"Positional Line 3":{"type":3,"Enabled":false,"refY":3.0,"radius":0.0,"color":4294967295,"refActorType":2,"includeRotation":true,"AdditionalRotation":3.9269907,"LineAddHitboxLengthYA":true,"LineAddPlayerHitboxLengthYA":true},"Positional Line 4":{"type":3,"Enabled":false,"refY":3.0,"radius":0.0,"color":4294967295,"refActorType":2,"includeRotation":true,"AdditionalRotation":5.497787,"LineAddHitboxLengthYA":true,"LineAddPlayerHitboxLengthYA":true}},"JobLock":710288080926}
```
Attack Range Ring (Ranged Jobs Only)
```
Attack Range Rings (Ranged Jobs Only)~{"Elements":{"20y Ring":{"type":1,"radius":20.0,"color":4294967295,"refActorType":2,"includeHitbox":true,"includeOwnHitbox":true}},"JobLock":1488734650592}
```
6 Yalm Attack Range Ring (Samurai/Sage Only)
```
Attack Range Rings (SAM/SGE Only)~{"Elements":{"6y Ring":{"type":1,"radius":6.0,"color":4294967295,"refActorType":2,"includeHitbox":true,"includeOwnHitbox":true}},"JobLock":1116691496960}
```
Attack Range Rings (Positional Jobs Only)
```
Attack Range Rings (Positional Jobs Only)~{"Elements":{"Melee Action Range":{"type":1,"radius":3.0,"color":4294967295,"refActorType":2,"includeHitbox":true,"includeOwnHitbox":true},"Melee Auto-Attack Range":{"type":1,"Enabled":false,"radius":3.1,"color":4294967295,"refActorType":2,"includeHitbox":true,"includeOwnHitbox":true},"Positional Line 1":{"type":3,"refY":3.0,"radius":0.0,"color":4294967295,"refActorType":2,"includeRotation":true,"AdditionalRotation":0.7853982,"LineAddHitboxLengthYA":true,"LineAddPlayerHitboxLengthYA":true},"Positional Line 2":{"type":3,"refY":3.0,"radius":0.0,"color":4294967295,"refActorType":2,"includeRotation":true,"AdditionalRotation":2.3561945,"LineAddHitboxLengthYA":true,"LineAddPlayerHitboxLengthYA":true},"Positional Line 3":{"type":3,"refY":3.0,"radius":0.0,"color":4294967295,"refActorType":2,"includeRotation":true,"AdditionalRotation":3.9269907,"LineAddHitboxLengthYA":true,"LineAddPlayerHitboxLengthYA":true},"Positional Line 4":{"type":3,"refY":3.0,"radius":0.0,"color":4294967295,"refActorType":2,"includeRotation":true,"AdditionalRotation":5.497787,"LineAddHitboxLengthYA":true,"LineAddPlayerHitboxLengthYA":true}},"JobLock":551371669524}
```

**Comment by F-a-y-t-h** [comment]
Auto attack range (about 2.09y) is smaller then the max range for abilities (3y) (+target hitbox size); something you can easily tell by just a striking dummy or a caster mob.... 

![image](https://puu.sh/J517R/b75218be2a.png)
![image](https://puu.sh/J517I/a380c7073c.png)
Auto-attacks stop at yellow line, red line still allows gcd's

**Comment by SashaFFXIV** [comment]
_sigh_

Striking Dummies are the reason why range and hitbox misconceptions exist. Their hitboxes are incorrect and do not function correctly. This is the same reason why if you use a line/cone attack against a Striking Dummy at maximum range it will miss even though that behavior will not occur against any other enemy in the game. The game reports their hitboxes to be larger than they actually are.

In my original post you can see images of me testing against a boss. The inner line of the second picture is GCD range. The outer line of the second picture is 3.1 yalms, and you can see me auto-attacking from that point. Test it on anything that isn't a Striking Dummy and you'll see that I am correct.

**Comment by Eternita-S** [comment]
You can test with striking dummy in explorer mode dungeon, they are correct.
@SashaFFXIV thank you for contribution, I will add it shortly
