### ISSUE TITLE
Feature Request: Advanced Targeting Options

### ISSUE THREAD

**Issue by ghost** [Eternita-S/Splatoon#51]
Specific Party Members: Allow to target P2, P3, P4 ... P8

ToT: Modulate targeting to target the original target's target (Eg. Select boss by name but actually target the tank that the boss is targeting)

Target by buff ID: Target all entities that currently have a buff ID matching the one entered. Not sure how practical this is as it may be quite resource intensive.

**Comment by Eternita-S** [comment]
Sometimes it's fine to sacrifice some performance I suppose, so buff id was added now. As for party members or target of target that will be added at a later time.

**Comment by Eternita-S** [comment]
All requested features have been added and will be available soon
