### ISSUE TITLE
[Bug] 'Filled' checkbox cannot be toggled on elements if multiple elements are open at once.

### ISSUE THREAD

**Issue by ghost** [Eternita-S/Splatoon#54]
Happens on all elements that are open except for the first open element in the layout.

2 elements open. Click, does not enable.
![image](https://user-images.githubusercontent.com/55117631/173490391-8434bf0a-5e12-47fd-8264-a95e6257b845.png)

Close first element. Click, enables.
![image](https://user-images.githubusercontent.com/55117631/173490522-67a30224-7f63-4a10-973b-4e0db56bdb29.png)

**Comment by Eternita-S** [comment]
Will be fixed in next version, thanks!
