### ISSUE TITLE
Feature Request: Donut Element

### ISSUE THREAD

**Issue by ghost** [Eternita-S/Splatoon#57]
Currently I'm resorting to drawing faint outer circles to indicate any kind of donut mechanic but being able to fill a donut shaped area would be a lot easier and look a lot nicer than just drawing concentric rings.

**Comment by Eternita-S** [comment]
I could only make it like it is with cone element now, if it's going to be any help

**Comment by Eternita-S** [comment]
Added and will be available shortly
